import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, HeadContent, Scripts, useRouter, type ErrorComponentProps } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
function ErrorComponent({ error, reset }: ErrorComponentProps) { const router=useRouter(); useEffect(()=>{reportLovableError(error,{boundary:"root"})},[error]); return <div className="min-h-screen grid place-items-center p-6 text-center"><div><h1 className="text-2xl font-bold">Não foi possível carregar a página.</h1><p className="mt-2">Tente atualizar a página.</p><button className="mt-5 rounded-lg bg-[#1D4ED8] px-5 py-3 text-white" onClick={()=>{router.invalidate();reset()}}>Tentar novamente</button></div></div> }
function NotFound(){return <div className="min-h-screen grid place-items-center text-center"><div><h1 className="text-6xl font-black text-[#1D4ED8]">404</h1><p className="my-4">Página não encontrada.</p><Link to="/" className="text-[#1D4ED8] font-bold">Voltar ao início</Link></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{title:"Casa dos Bichos - Pet Shop | Vila Tupi, Praia Grande"},{name:"description",content:"Casa dos Bichos - Pet Shop em Vila Tupi, Praia Grande. Banho, tosa, rações, acessórios, produtos e entregas com atendimento próximo."},{name:"author",content:"Casa dos Bichos - Pet Shop"},{property:"og:title",content:"Casa dos Bichos - Pet Shop | Vila Tupi, Praia Grande"},{property:"og:description",content:"Cuidado completo para seu pet com atendimento próximo, produtos, banho, tosa e entregas."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"stylesheet",href:appCss}]}),shellComponent:RootShell,component:Root,notFoundComponent:NotFound,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="pt-BR"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function Root(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><Outlet/></QueryClientProvider>}
